// <auto-generated />
namespace sliontek_web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addbuynewlog4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addbuynewlog4));
        
        string IMigrationMetadata.Id
        {
            get { return "201806080318047_add-buy-new-log4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
